export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';
export const COURSE_SECTION_TASKS = 'COURSE_SECTION_TASKS';
export const COURSE_SECTION_STUDENTS = 'COURSE_SECTION_STUDENTS';
export const COURSE_SECTION_MEETINGS = 'COURSE_SECTION_MEETINGS';

export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// modals
export const ADD_COURSE_MODAL = 'ADD_COURSE_MODAL';
export const ADD_MEETING_MODAL = 'ADD_MEETING_MODAL';
export const ADD_STUDENT_MODAL = 'ADD_STUDENT_MODAL';
export const ADD_TASK_MODAL = 'ADD_TASK_MODAL';
export const SETTINGS_MODAL = 'SETTINGS_MODAL';
export const EMAIL_TEMPLATES_MODAL = 'EMAIL_TEMPLATES_MODAL';
