export const SET_ALL_COURSES = 'SET_ALL_COURSES';
export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE';

export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE_DETAIL = 'UPDATE_COURSE_DETAIL';
export const DELETE_COURSE = 'DELETE_COURSE';

export const ADD_STUDENT_TO_COURSE = 'ADD_STUDENT_TO_COURSE';
export const UPDATE_STUDENT_DETAIL = 'UPDATE_STUDENT_DETAIL';
export const DELETE_STUDENT = 'DELETE_STUDENT';

export const ADD_MEETING_TO_COURSE = 'ADD_MEETING_TO_COURSE';
export const UPDATE_MEETING_DETAIL = 'UPDATE_MEETING_DETAIL';
export const DELETE_MEETING = 'DELETE_MEETING';

export const SET_CALENDLY_MEETINGS_FOR_COURSE = 'SET_CALENDLY_MEETINGS_FOR_COURSE';
